### ISSUE TITLE
Ep22 : Flask 인스타그램 클론코딩 (12)

### ISSUE THREAD

**Issue by TGoddessana** [IDU-IFP/ifp-flask-study#31]
#### (과제2) 이전에 Backend 서버를 배포할 때에는 github action 으로 우리만의 배포 전략을 구성했습니다. 이번에도, 어떤 액션을 수행하면 배포가 자동으로 진행되게끔 workflow 파일을 구성한 다음, 댓글로 파일과 함께 설명을 해 주시면 됩니다!

- 참고자료 1
[flastagram-frontend-server.fly.dev](https://flastagram-frontend-server.fly.dev/flastagram/login)

- 참고자료 2
https://gdsanadev.com/planguages/real-python-flask-%ec%9d%b8%ec%8a%a4%ed%83%80%ea%b7%b8%eb%9e%a8-%ed%81%b4%eb%a1%a0%ec%bd%94%eb%94%a9-instagram-clone-12/

**Comment by overtae** [comment]
- 과제1
  https://flastagram-ffe-server.fly.dev/flastagram/login
- 과제2
  ```
  steps:
  - uses: actions/checkout@v3
  - uses: superfly/flyctl-actions/setup-flyctl@master
  - run: cd backend && flyctl deploy --remote-only
  - run: cd frontend && flyctl deploy --remote-only
  ```

**Comment by youngjoo00** [comment]
- 과제 1
[https://flastagram.fly.dev/flastagram/login](url)

**Comment by 2gang** [comment]
* 과제1
https://flask-instagram-frontend-server.fly.dev/flastagram/login

*과제2
```
steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: cd backend && flyctl deploy --remote-only
        - run: cd frontend && flyctl deploy --remote-only
```
